api/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import apps.core.views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello', core_views.return_hello),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^patients/', include('apps.patients.urls', namespace='patients')),
    url(r'^med_tests/', include('apps.med_tests.urls', namespace='med_tests')),
    url(r'^appointments/', include('apps.appointments.urls', namespace='appointments')),
    url(r'^diagnosis/', include('apps.diagnosis.urls', namespace='diagnosis')),
    url(r'^reports/', include('apps.reports.urls', namespace='reports')),
    url(r'^analytics/', include('apps.analytics.urls', namespace='analytics'))
]

api/apps/appointments/urls.py
from django.conf.urls import url

from apps.appointments.views import *

urlpatterns = [
    url(r'^create$', create_action, name='create'),
    url(r'^show/(?P<appointment_id>\d+)$', show_action, name='show'),
    url(r'^finish/(?P<appointment_id>\d+)$', finish_action, name='finish'),
    url(r'^cancel/(?P<appointment_id>\d+)$', cancel_action, name='cancel'),
]

api/apps/patients/urls.py
from django.conf.urls import url

from apps.patients.views import *

urlpatterns = [
    url(r'^list$', list_action, name='list'),
    url(r'^tests$', tests_action, name='tests'),
    url(r'^appointments$', appointments_action, name='appointments'),
    url(r'^create$', create_action, name='create'),
    url(r'^update$', update_action, name='update'),
    url(r'^show/(?P<patient_id>\d+)$', show_action, name='show'),
    url(r'^delete/(?P<patient_id>\d+)$', delete_action, name='delete'),
    url(r'(?P<patient_id>\d+)/tests$', patient_test_action, name='patient_tests'),
    url(r'(?P<patient_id>\d+)/dynamics$', patient_dynamics_action, name='patient_dynamics'),
    url(r'(?P<patient_id>\d+)/appointments$', patient_appointments_action, name='patient_appointments'),
    url(r'(?P<patient_id>\d+)/diagnosis$', patient_diagnosis_action, name='patient_diagnosis'),
]

api/apps/appointments/models.py
from django.db import models

# Create your models here.

api/apps/core/models.py
# -*- coding: utf-8 -*- 
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.postgres.fields import *
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from transliterate import translit
from datetime import date, timedelta
from django.conf import settings
import os

from apps.core.managers import UserManager

GENDER = (
    ('Мужской', 'Мужской'),
    ('Женский', 'Женский')
)

BLOOD_GROUP = (
    ('I', 'I'),
    ('II', 'II'),
    ('III', 'III'),
    ('IV', 'IV')
)

RH_FACTOR = (
    ('Rh+', 'Rh+'),
    ('Rh-', 'Rh-')
)

APPOINTMENT_STATUS = (
    ('Назначено', 'Назначено'),
    ('Завершено', 'Завершено'),
    ('Отменено', 'Отменено')
)

DIAGNOSIS_TYPE = (
    ('Предварительный', 'Предварительный'),
    ('Клинический', 'Клинический'),
    ('Окончательный', 'Окончательный')
)

USER_ROLES = (
    ('ADMIN', 'ADMIN'),
    ('DOCTOR', 'DOCTOR')
)


def attachment_file_path(instance, filename):
    return os.path.join('attachments', instance.id, filename)


class AbstractModel(models.Model):
    id = models.AutoField(primary_key=True)

    class Meta:
        abstract = True


class User(AbstractBaseUser, PermissionsMixin):
    email = models.CharField(verbose_name=_('Email'), max_length=30, unique=True)
    name = models.CharField(verbose_name=_('Имя'), max_length=30)
    surname = models.CharField(verbose_name=_('Фамилия'), max_length=30)
    patronymic = models.CharField(verbose_name=_('Отчество'), max_length=30, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(_('Администратор?'), default=False)
    date_joined = models.DateTimeField(default=now())
    role = models.CharField(verbose_name=_('Роль'), max_length=20, choices=USER_ROLES, default='DOCTOR')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'user'
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

    def get_short_name(self):
        return '%s %s' % (self.name, self.surname)

    def get_full_name(self):
        return '%s' % self.name


class Address(AbstractModel):
    post_code = models.CharField(max_length=30, verbose_name='Post code')
    country = models.CharField(max_length=100, verbose_name='Country')
    region = models.CharField(max_length=100, verbose_name='Region')
    city = models.CharField(max_length=100, verbose_name='City')
    street = models.CharField(max_length=150, verbose_name='Street')

    class Meta:
        db_table = 'address'
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')


class OmiCard(AbstractModel):
    number = models.CharField(max_length=16, verbose_name='Number')
    expire_date = models.DateField(verbose_name='Expiration date')
    insurance_org = models.CharField(max_length=150, verbose_name='Insurance Organization')

    class Meta:
        db_table = 'omi_card'
        verbose_name = _('OMI Card')
        verbose_name_plural = _('OMI Cards')


class Patient(AbstractModel):
    name = models.CharField(verbose_name=_('Имя'), max_length=50)
    surname = models.CharField(verbose_name=_('Фамилия'), max_length=50)
    patronymic = models.CharField(verbose_name=_('Отчество'), max_length=50, blank=True, null=True)
    gender = models.CharField(verbose_name=_('Пол'), max_length=20, choices=GENDER)
    birthday = models.DateField(verbose_name=_('Дата рождения'))
    blood_group = models.CharField(verbose_name=_('Группа крови'), max_length=20, choices=BLOOD_GROUP, blank=True,
                                   null=True)
    rh_factor = models.CharField(verbose_name=_('Резус-фактор'), max_length=20, choices=RH_FACTOR, blank=True,
                                 null=True)
    is_disabled = models.BooleanField(verbose_name=_('Инвалидность'), default=False)
    omi_card = models.CharField(verbose_name=_('ОМС'), max_length=30, blank=True, null=True)
    address = models.CharField(verbose_name=_('Адрес проживания'), max_length=255, blank=True, null=True)
    occupation = models.CharField(verbose_name=_('Род деятельности'), max_length=100, blank=True, null=True)
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='patients', on_delete=models.CASCADE)

    @property
    def age(self):
        return (date.today() - self.birthday) // timedelta(days=365.2425)

    @property
    def short_name(self):
        if self.patronymic is not None and self.patronymic != '':
            return '%s %s %s' % (self.surname, self.name[0], self.patronymic[0])
        else:
            return '%s %s.' % (self.surname, self.name[0])

    @property
    def short_info(self):
        return '%s (ОМС № %s)' % (self.short_name, self.omi_card)

    @property
    def full_name(self):
        if self.patronymic is not None and self.patronymic != '':
            return '%s %s %s' % (self.surname, self.name, self.patronymic)
        else:
            return '%s %s' % (self.surname, self.name)

    def __str__(self):
        return self.short_info

    def __repr__(self):
        return self.short_info

    class Meta:
        db_table = 'patient'
        verbose_name = _('Пациент')
        verbose_name_plural = _('Пациенты')


class BaseMedType(AbstractModel):
    name = models.CharField(max_length=200, verbose_name=_('Название'))
    short_name = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name=_('Идентификатор'))
    description = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Описание'))

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class MedArea(BaseMedType):
    parent = models.ForeignKey('core.MedArea', blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(MedArea, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'med_area'
        verbose_name = _('Медицинская область')
        verbose_name_plural = _('Медицинские области')


class MedTest(BaseMedType):
    med_area = models.ForeignKey('core.MedArea')

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_area.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(
                ' ', '_')
        super(MedTest, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'med_test'
        verbose_name = _('Тип обследования')
        verbose_name_plural = _('Типы обследования')


class RealInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='real_inds')
    min_norm = models.FloatField(blank=True, null=True, verbose_name=_('Минимальная норма'))
    max_norm = models.FloatField(blank=True, null=True, verbose_name=_('Максимальная норма'))
    min_critical = models.FloatField(blank=True, null=True, verbose_name=_('Минимальная критическая норма'))
    max_critical = models.FloatField(blank=True, null=True, verbose_name=_('Максимальная критическая норма'))
    unit = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Единица измерения'))

    class Meta:
        db_table = 'real_ind'
        verbose_name = _('Вещественный показатель')
        verbose_name_plural = _('Вещественные показатели')

    def save(self, *args, **kwargs):
        if self.min_norm is None or self.max_norm is None:
            pass
        elif self.min_norm > self.max_norm:
            raise ValidationError("Min norm must be less than max norm")
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(
                ' ', '_')
        super(RealInd, self).save(*args, **kwargs)


class IntInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='int_inds')
    min_norm = models.IntegerField(blank=True, null=True, verbose_name=_('Минимальная норма'))
    max_norm = models.IntegerField(blank=True, null=True, verbose_name=_('Максимальная норма'))
    min_critical = models.IntegerField(blank=True, null=True, verbose_name=_('Минимальная критическая норма'))
    max_critical = models.IntegerField(blank=True, null=True, verbose_name=_('Максимальная критическая норма'))
    unit = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Единица измерения'))

    class Meta:
        db_table = 'int_ind'
        verbose_name = _('Целый показатель')
        verbose_name_plural = _('Целые показатели')

    def save(self, *args, **kwargs):
        if self.min_norm is None or self.max_norm is None:
            pass
        elif self.min_norm > self.max_norm:
            raise ValidationError("Min norm must be less than max norm")
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(
                ' ', '_')
        super(IntInd, self).save(*args, **kwargs)


class TextInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='text_inds')
    values = ArrayField(models.CharField(max_length=255), null=True, blank=True, verbose_name=_('Принимаемые значения'))

    class Meta:
        db_table = 'text_ind'
        verbose_name = _('Строковой показатель')
        verbose_name_plural = _('Строковые показатели')

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':

api/apps/patients/models.py
from django.db import models

# Create your models here.

api/apps/appointments/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.appointments.forms import AppointmentForm
from apps.core.models import Appointment


@login_required
def create_action(request):
    if request.method == 'GET':
        return render(request, 'appointments/create.html', {})
    else:
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save_appointment(request.POST.get('patient_id'))
            return redirect(reverse('patients:appointments'))
    return render(request, 'appointments/create.html', {})


@login_required
def show_action(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    patient = appointment.patient
    return render(request, 'appointments/show.html', {'appointment': appointment, 'patient': patient})


@login_required
def finish_action(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.info = request.POST.get('info', None)
    appointment.complaints = request.POST.get('complaints', None)
    appointment.status = 'Завершено'
    appointment.save()
    return redirect(reverse('patients:appointments'))


@login_required
def cancel_action(request, appointment_id):
    appointment = Appointment.objects.get(pk=appointment_id)
    appointment.status = 'Отменено'
    appointment.save()
    return redirect(reverse('patients:appointments'))

api/apps/patients/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.core.models import Patient, TestRec, Appointment, Diagnosis
from apps.patients.forms import PatientForm

User = get_user_model()


@login_required
def list_action(request):
    search_full_name = request.GET.get('search_full_name', '')
    patients = request.user.patients.all()
    patients = [patient for patient in patients if search_full_name in patient.full_name]
    return render(
        request,
        'patients/list.html',
        {
            'patients': patients,
            'patients_count': len(patients)
        }
    )


@login_required
def tests_action(request):
    patients_count = request.user.patients.count()
    tests = TestRec.objects.filter(patient__doctor_id=request.user.id)
    return render(
        request,
        'patients/tests.html',
        {
            'patients_count': patients_count,
            'tests': tests
        }
    )


@login_required
def patient_test_action(request, patient_id):
    patient = Patient.objects.get(pk=patient_id)
    tests = patient.test_recs
    return render(
        request,
        'patients/patient_tests.html',
        {
            'patient': patient,
            'tests': tests
        }
    )


@login_required
def patient_dynamics_action(request, patient_id):
    patient = Patient.objects.get(pk=patient_id)
    tests = patient.test_recs
    return render(
        request,
        'patients/patient_dynamics.html',
        {
            'patient': patient,
            'tests': tests
        }
    )


@login_required
def appointments_action(request):
    patients_count = request.user.patients.count()
    appointments = Appointment.objects.filter(patient__doctor_id=request.user.id)
    return render(
        request,
        'patients/appointments.html',
        {
            'patients_count': patients_count,
            'appointments': appointments
        }
    )


@login_required
def patient_appointments_action(request, patient_id):
    patients_count = request.user.patients.count()
    patient = Patient.objects.get(pk=patient_id)
    return render(
        request,
        'patients/patient_appointments.html',
        {
            'patients_count': patients_count,
            'patient': patient
        }
    )


@login_required
def patient_diagnosis_action(request, patient_id):
    patients_count = request.user.patients.count()
    patient = Patient.objects.get(pk=patient_id)
    return render(
        request,
        'patients/patient_diagnosis.html',
        {
            'patients_count': patients_count,
            'patient': patient
        }
    )


@login_required
def create_action(request):
    if request.method == 'POST':
        form = PatientForm(request)
        if form.is_valid():
            form.save()
        return redirect(reverse('patients:list'))
    else:
        return render(request, 'patients/create.html', {})


@login_required
def show_action(request, patient_id):
    patient = Patient.objects.get(pk=patient_id)
    return render(request, 'patients/show.html', {
        'patient': patient
    })


@login_required
def update_action(request):
    patient_id = None
    if request.method == 'POST':
        patient_id = int(request.POST['patient_id'])
        form = PatientForm(request)
        if form.is_valid():
            form.update()
    return redirect(reverse('patients:show', kwargs={'patient_id': patient_id}))


@login_required
def delete_action(request, patient_id):
    if request.method == 'POST':
        patient = Patient.objects.get(pk=patient_id)
        patient.delete()
        return HttpResponseRedirect(reverse('patients:list'))
    return redirect(reverse('patients:show', kwargs={'patient_id': patient_id}))

api/templates/patients/create.html
{% extends 'core/base_menu.html' %}
{% load staticfiles %}
{% block header %}
    <style>
        body {
            padding-top: 90px;
        }

        .form-group.required .form-control-label:after {
            content: "*";
            color: red;
        }

        .btn {
            width: 100%;
        }
    </style>
    <link rel="stylesheet" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.css.map' %}">
{% endblock %}
{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            Создание медкарты пациента
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" id="id_patient">
                {% csrf_token %}
                <fieldset>
                    <legend>ФИО</legend>
                    <div class="form-group row required">
                        <label for="id_name" class="col-sm-2 form-control-label">Имя: </label>
                        <div class="col-sm-4">
                            <input id="id_name" name="name" class="form-control" style="background-color: #ffffff"/>
                        </div>
                        <label for="id_surname" class="col-sm-2 form-control-label">Фамилия: </label>
                        <div class="col-md-4">
                            <input id="id_surname" name="surname" class="form-control"
                                   style="background-color: #ffffff"/>
                        </div>
                    </div>
                    <div class="form-group row required">
                        <label for="id_patronymic" class="col-sm-2 form-control-label">Отчество: </label>
                        <div class="col-md-4">
                            <input id="id_patronymic" name="patronymic" class="form-control"
                                   style="background-color: #ffffff"/>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Основные сведения о пациенте</legend>
                    <div class="form-group row required">
                        <label for="id_gender" class="col-sm-2 form-control-label">Пол: </label>
                        <div class="col-sm-4">
                            <select id="id_gender" class="form-control" name="gender">
                                <option value="Мужской">мужской</option>
                                <option value="Женский">женский</option>
                            </select>
                        </div>
                        <label for="id_birthday" class="col-sm-2 form-control-label">Дата рождения: </label>
                        <div class="col-sm-4">
                            <input id="id_birthday" name="birthday" class="form-control"
                                   style="background-color: #ffffff"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_address" class="col-sm-2 form-control-label">Адрес проживания: </label>
                        <div class="col-sm-4">
                            <textarea id="id_address" name="address" class="form-control"></textarea>
                        </div>
                        <label for="id_occupation" class="col-sm-2 form-control-label">Род деятельности: </label>
                        <div class="col-sm-4">
                            <input id="id_occupation" name="occupation" class="form-control"
                                   style="background-color: #ffffff"/>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Медицинские данные</legend>
                    <div class="form-group row required">
                        <label for="id_omi_card" class="col-sm-2 form-control-label">ОМС: </label>
                        <div class="col-sm-4">
                            <input id="id_omi_card" data-mask="9999-9999-9999-9999" name="omi_card" class="form-control"
                                   style="background-color: #ffffff"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_disabled" class="col-sm-2 form-control-label">Инвалидность: </label>
                        <div class="col-sm-2">
                            <select id="id_disabled" name="is_disabled" class="form-control"
                                    style="background-color: #ffffff">
                                <option value="False">Не имеется</option>
                                <option value="True">Имеется</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_blood_group" class="col-sm-2 form-control-label">Группа крови: </label>
                        <div class="col-sm-2">
                            <select id="id_blood_group" name="blood_group" class="form-control">
                                <option value="I">I</option>
                                <option value="II">II</option>
                                <option value="III">III</option>
                                <option value="IV">IV</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_rh_factor" class="col-sm-2 form-control-label">Резус-фактор: </label>
                        <div class="col-sm-2">
                            <select id="id_rh_factor" name="rh_factor" class="form-control">
                                <option value="Rh+">положительный</option>
                                <option value="Rh-">отрицательный</option>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="panel-footer">
            <div class="form-group row">
                <div class="col-md-9">

                </div>
                <div class="col-md-3">
                    <button class="btn btn-success" type="button" onclick="$('#id_patient').submit();">Создать медкарту
                        пациента
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <link rel="stylesheet" href="{% static 'jasny-bootstrap/css/jasny-bootstrap.min.css' %}">
    <script src="{% static 'jasny-bootstrap/js/jasny-bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script>
        $('.omi_card').inputmask({
            mask: '9999-9999-9999-9999'
        });
        $('#id_birthday').datepicker({
            format: 'yyyy-mm-dd',
            language: 'ru',
            orientation: 'bottom'
        });
    </script>
{% endblock %}

api/templates/patients/patient_diagnosis.html
{% extends 'patients/patient_sidebar.html' %}
{% load staticfiles %}
{% block main %}
    <div class="row">
        <div class="col-sm-2">
            <a class="btn btn-success"
               href="{% url 'diagnosis:create' patient_id=patient.id %}">
                Добавить диагноз
            </a>
        </div>
    </div>
    <br/>
    {% if patient.diagnosis.count != 0 %}
        <table class="table table-bordered" cellpadding="0">
            <thead>
                <tr>
                    <th>Диагноз</th>
                    <th>Дата диагноза</th>
                    <th>Вид диагноза</th>
                    <th>Краткая информация</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for diagnosis in patient.diagnosis.all %}
                    <tr>
                        <td>{{ diagnosis.diagnosis }}</td>
                        <td>{{ diagnosis.diagnosis_date }}</td>
                        <td>{{ diagnosis.diagnosis_type }}</td>
                        <td>{{ diagnosis.summary|default_if_none:"-" }}</td>
                        <td>
                            <a href="{% url 'diagnosis:show' diagnosis_id=diagnosis.id %}"
                               class="btn btn-success">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                            <a onclick="deleteTest('{% url 'diagnosis:delete' diagnosis_id=diagnosis.id %}');"
                               class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            У пациента нет ни одного диагноза. <a href="{% url 'diagnosis:create' patient_id=patient.id %}">Добавить диагноз?</a>
        </div>
    {% endif %}
    <script src="{% static 'bootbox/bootbox.js' %}"></script>
    <script>
        $('#id_diagnosis_nav_item').addClass('active');
    </script>
    <script>

    </script>
{% endblock %}

api/templates/patients/patient_sidebar.html
{% extends 'core/base_menu_fluid.html' %}
{% block header %}
    <style>
        body {
            padding-top: 80px;
        }

        .bg-light {
            background-color: #f8f9fa !important;
        }

        .d-sm-block {
            display: block !important;
        }

        .d-sm-block {
            display: block !important;
        }

        .flex-column {
            -ms-flex-direction: column !important;
            flex-direction: column !important;
        }

        .sidebar {
            padding-left: 0;
            padding-right: 0;
        }

        .sidebar {
            position: fixed;
            top: 51px;
            bottom: 0;
            left: 0;
            z-index: 1000;
            padding-top: 10px;
            overflow-x: hidden;
            overflow-y: auto;
            border-right: 1px solid #eee;
        }

        .sidebar .nav-item {
            width: 100%;
        }

        .nav {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            padding-left: 0;
            margin-bottom: 0;
            list-style: none;
        }

        .link {
            display: block;
            padding: .5rem 1rem;
        }

        .sidebar .link {
            border-radius: 0;
        }

        .nav-item > a {
            border-bottom: 1px solid #e1e4e8;
        }

        .nav-pills > li + li {
            margin-left: 0;
        }

        .nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover {
            border-left: 4px solid #e36209;
            background-color: #eee;
            color: #0f0f0f;
        }

        .counter {
            display: inline-block;
            padding: 2px 5px;
            font-size: 12px;
            font-weight: 600;
            line-height: 1;
            color: #586069;
            background-color: rgba(27, 31, 35, 0.08);
            border-radius: 20px;
        }

        main {
            margin-left: 17%;
        }

        h1 {
            margin-bottom: 20px;
            padding-bottom: 9px;
            border-bottom: 1px solid #eee;
        }
    </style>
{% endblock %}

{% block header2 %}

{% endblock %}

{% block content %}
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li id="id_patient_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'patients:show' patient_id=patient.id %}'" class="link">Основная информация о пациенте</a>
                </li>
                <li id="id_tests_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'patients:patient_tests' patient_id=patient.id %}'" class="link">Обследования</a>
                </li>
                <li id="id_dynamics_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'patients:patient_dynamics' patient_id=patient.id %}'" class="link">Динамика</a>
                </li>
                <li id="id_diagnosis_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'patients:patient_diagnosis' patient_id=patient.id %}'" class="link">Диагнозы</a>
                </li>
                <li id="id_appointments_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'patients:patient_appointments' patient_id=patient.id %}'" class="link">Приемы</a>
                </li>
            </ul>
        </nav>
        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 tab-content">
            {% block main %}
            {% endblock %}
        </main>
    </div>
{% endblock %}